version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      dev-tools:
        patterns:
          - "phpunit/phpunit"
          - "phpstan/phpstan"
          - "rector/*"
          - "laravel/pint"
          - "infection/infection"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
